server:
  port: 8013

spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/wangshengsheng/config-repo.git
          #username: 如果是私有仓库写仓库的用户名
          #password: 如果是私有仓库写仓库的密码
    loadbalancer:
      ribbon:
        enabled: false
  profiles:
    active: dev
management:
  endpoints:
    web:
      exposure:
        include: "*"

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

