server:
  port: 8889
spring:
  application:
    name: cloud-gateway-eureka
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
#      routes:
#        - id: add_request_parameter_route
#          uri: http://localhost:9003
#          #格式为：lb://应用注册服务名
#          uri: lb://spring-cloud-producer
#          filters:
#            - AddRequestParameter=foo, bar
#          predicates:
#            - Method=GET

      # 当请求路径匹配到/name/**会将包含name和后边的字符串接去掉转发， StripPrefix=2就代表截取路径的个数，
      # 这样配置后当请求/name/bar/foo后端匹配到的请求路径就会变成http://nameservice/foo
#      routes:
#        - id: nameRoot
#          uri: lb://spring-cloud-producer
#          # 果请求与断言相匹配则进行路由。
#          predicates:
#            - Path=/name/**
#          filters:
#            - StripPrefix=2
      routes:
        - id: prefixpath_route
          uri: lb://spring-cloud-producer
          predicates:
            - Method=GET
          filters:
            - PrefixPath=/mypath


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
logging:
  level:
    org.springframework.cloud.gateway: debug


#  1.spring.cloud.gateway.discovery.locator.enabled：是否与服务注册于发现组件进行结合，
#  2.通过 serviceId 转发到具体的服务实例。默认为 false，设为 true 便开启通过服务中心的自动根据 serviceId 创建路由的功能。
#  3.eureka.client.service-url.defaultZone指定注册中心的地址，以便使用服务发现功能
#  logging.level.org.springframework.cloud.gateway 调整相 gateway 包的 log 级别，以便排查问题
